# version: '3'

volumes:
  pg_data_prod:
  static_vol:
  media_vol:

services:
  
  db:
    image: postgres:13
    env_file: ./.env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  backend:
    container_name: foodgram_back
    image: and2510/foodgram_back
    env_file: ./.env
    volumes:
      - static_vol:/backend_static
      - media_vol:/app/media
    depends_on:
      - db
  
  frontend:
    container_name: foodgram_front
    image: and2510/foodgram_front
    env_file: ./.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_vol:/frontend_static
    depends_on:
      - backend
  
  nginx:
    container_name: foodgram_proxy
    image: and2510/foodgram_proxy
    ports:
      - "8000:80"
    volumes:
      - static_vol:/static
      - media_vol:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
