# Модели Users
FIRST_NAME_MAX_LENGTH = LAST_NAME_MAX_LENGTH = 150
USERNAME_MAX_LENGTH = 150
EMAIL_MAX_LENGTH = 254

# Модели Recipes
INGRED_NAME_MAX_LENGTH = 128
MEASUR_UNIT_NAME_MAX_LENGTH = 64
TAG_NAME_MAX_LENGTH = TAG_SLUG_MAX_LENGTH = 32
RECIPE_NAME_MAX_LENGTH = 256

# диапазон от 0 до 32767 для полей PositiveSmallIntegerField
COOKING_TIME_MIN_VALUE = AMOUNT_MIN_VALUE = 1
COOKING_TIME_MAX_VALUE = AMOUNT_MAХ_VALUE = 32760
