# Generated by Django 3.2.3 on 2024-09-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_avatar.jpeg', null=True, upload_to='media/avatar', verbose_name='Аватарка'),
        ),
    ]
